spring.application.name=coding-challenge
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:9876/movies
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update